### PR TITLE
chore: add entrypoint and build pipeline

### LINKED ISSUE #24: Example pipeline should have on-pr-{{revision}} on output-image

### PR DESCRIPTION
**Pull request by avi-biton**
Closes #24

### CODE REVIEW

**Review by yftacherzog — APPROVED** [review]

**Comment by yftacherzog** [comment]
@ralphbean can you delete the branch protection rule for the pipelinerun that you deleted?

**Review by ralphbean — APPROVED** [review]
@avi-biton, @yftacherzog do you need any additional rights in github to self-manage merging changes to this repo?

**Comment by ralphbean** [comment]
OK - you should both be added now at https://github.com/konflux-ci/testrepo/settings/access

**Comment by yftacherzog** [comment]
> @avi-biton, @yftacherzog do you need any additional rights in github to self-manage merging changes to this repo?

Thanks! We realized a gap just before the end of the day yesterday. Ot should be addressed now but we didn't want to merge it just before the weekend.

**Review by yftacherzog — APPROVED** [review]

**Pull request merged**
